version: '3.6'
services:
  web:
    build:
      context: .
      args:
        REQUIREMENTS_FILE: dev-requirements.txt
    volumes:
      - requirements:/opt/venv/bin
      - .:/app
    entrypoint:
      [
        "gunicorn",
        "--chdir",
        "/app",
        "app:app",
        "-w 1",
        "--threads",
        "1",
        "-b",
        "0.0.0.0:8000"
      ]
    ports:
      - 8000:8000
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=development
      - TEMPLATES_AUTO_RELOAD=True
      - PYTHONUNBUFFERED=1
      - REQUIREMENTS_FILE=dev-requirements.txt
volumes:
  requirements:
