version: '3.8'
services:
  vscode:
    user: fastapi-user
    image: lng-api-app:latest
    volumes:
      - .:/workspace:cached

    # Overrides default command so things don't shut down after the process ends.
    command: sh -c "while sleep 1000; do :; done"
