name: Lint

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  flake8_py3:
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Checkout code
        uses: actions/checkout@master
      - name: Run Flake8 Lint 
        run: docker-compose run --rm app sh -c "flake8"
      - name: Test
        run: docker-compose run --rm app sh -c "python -m pytest"


