on:
  pull_request:
    types: [opened, synchronize]

jobs:
  evaluator:
    runs-on: self-hosted
    steps:
      - name: Fetch project repository
        uses: actions/checkout@v2
      
      - name: Flake8 action
        uses: suo/flake8-github-action@v1